{
  "comments": [
    {
      "key": {
        "uuid": "fd41eb8f_cf691160",
        "filename": "java/com/google/gitiles/LogServlet.java",
        "patchSetId": 5
      },
      "lineNbr": 136,
      "author": {
        "id": 1019407
      },
      "writtenOn": "2019-05-09T17:52:50Z",
      "side": 0,
      "message": "I don\u0027t see where RevWalkException is now being handled.",
      "range": {
        "startLine": 136,
        "startChar": 4,
        "endLine": 136,
        "endChar": 34
      },
      "revId": "2fb3c19358bcf525f8068ef4386cf1af0a0bb526",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "4422651a_be8c6c99",
        "filename": "java/com/google/gitiles/LogServlet.java",
        "patchSetId": 5
      },
      "lineNbr": 136,
      "author": {
        "id": 1027112
      },
      "writtenOn": "2019-05-09T19:26:17Z",
      "side": 0,
      "message": "RevWalkException isA IOException, and it\u0027s a server error. It\u0027s handled as a server error in the DefaultErrorHandlingFilter.",
      "parentUuid": "fd41eb8f_cf691160",
      "range": {
        "startLine": 136,
        "startChar": 4,
        "endLine": 136,
        "endChar": 34
      },
      "revId": "2fb3c19358bcf525f8068ef4386cf1af0a0bb526",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "b7061037_ca50fcc3",
        "filename": "java/com/google/gitiles/LogServlet.java",
        "patchSetId": 5
      },
      "lineNbr": 136,
      "author": {
        "id": 1027112
      },
      "writtenOn": "2019-05-09T19:28:34Z",
      "side": 0,
      "message": "Actually, in this case, should I wrap it with GitilesRequestFailureException to avoid leakage?",
      "parentUuid": "4422651a_be8c6c99",
      "range": {
        "startLine": 136,
        "startChar": 4,
        "endLine": 136,
        "endChar": 34
      },
      "revId": "2fb3c19358bcf525f8068ef4386cf1af0a0bb526",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "839edab2_46294ae4",
        "filename": "java/com/google/gitiles/LogServlet.java",
        "patchSetId": 5
      },
      "lineNbr": 136,
      "author": {
        "id": 1019407
      },
      "writtenOn": "2019-05-10T00:10:29Z",
      "side": 0,
      "message": "I think it makes sense to wrap it in a GitilesRequestFailureException, but I have a feeling that there are lots of other paths where perhaps this very exception can be thrown but the \"throws IOException\" on every method signature is hiding it. I value consistency above the choice of where we draw the lines of abstraction. I don\u0027t see a big difference between handling RevWalkException vs. RepositoryNotFoundException in DefaultErrorHandlingFilter.",
      "parentUuid": "b7061037_ca50fcc3",
      "range": {
        "startLine": 136,
        "startChar": 4,
        "endLine": 136,
        "endChar": 34
      },
      "revId": "2fb3c19358bcf525f8068ef4386cf1af0a0bb526",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "7e0eab20_e34eb5b3",
        "filename": "java/com/google/gitiles/doc/DocServlet.java",
        "patchSetId": 5
      },
      "lineNbr": 128,
      "author": {
        "id": 1019407
      },
      "writtenOn": "2019-05-09T17:52:50Z",
      "side": 0,
      "message": "I had a question about where this is handled but I see  that it and RepositoryNotFound and ServiceMayNotContiue exceptions are all now handled in the DefaultErrorHandlinFilter class of the accompanying change.",
      "range": {
        "startLine": 128,
        "startChar": 6,
        "endLine": 128,
        "endChar": 33
      },
      "revId": "2fb3c19358bcf525f8068ef4386cf1af0a0bb526",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}